export const NOTIFICATION_STATUS_SUCCESS = "success";
export const NOTIFICATION_STATUS_ERROR = "error";
export const NOTIFICATION_TIME_SUCCESS = 1.5;
export const NOTIFICATION_TIME_ERROR = 5;

export default {
  NOTIFICATION_STATUS_SUCCESS,
  NOTIFICATION_STATUS_ERROR,
  NOTIFICATION_TIME_SUCCESS,
  NOTIFICATION_TIME_ERROR,
}